### ISSUE TITLE
Buttony vo widgetoch „O com to je“ a „Login“

### ISSUE THREAD

**Issue by j2ghz** [j2ghz/ChcemVediet-Style-Guide#11]
Buttony vo widgetoch „O com to je“ a „Login“ maju roznu velkost pisma = v nahladoch bola velkost pisma zvdy rovnaka. („Chcem vediet viac“ vs. „Prihlasit sa“)
Toto nie je jasne, preco sa tam vlastne vyskytli rozne
velkosti pisma v buttonoch? (nie su uz vsetky podla jedneho?)

![image](https://cloud.githubusercontent.com/assets/1708197/9941729/9175cc52-5d77-11e5-9408-2744e5aa7b75.png)

**Comment by j2ghz** [comment]
@mmmaly v prvom navrhu boli 3 tlacitka, biele pozadie, farebny text, na hover sa farby vymenia
v nahlade homepage bolo aj tlacitko prihlasit ktore malo farebne pozadie a biely text
v pripomienkach uz aj tlacitko registrovat s modrym pozadim a bielym textom
ako to s nimi teda bude? mam spravene tie 3 ktore su v casti 2, Buttons a tlacitko prihlasit je jednorazovo upravene. Mam pridat invertovane verzie vsetkych tlacitiek?

**Comment by lpk90901** [comment]
Ako som odpovedala pri #19 a #14 - spravme 3 druhy primary buttonov a 2 extra classy [ktore su kvoli homepage z vizualnych dovodov]

<img width="926" alt="primary-button" src="https://cloud.githubusercontent.com/assets/6820342/10043069/5cc19130-61f0-11e5-8462-5dfda08c5712.png">

extra classy:
"prihlasit sa" na homepage
<img width="274" alt="homepage login" src="https://cloud.githubusercontent.com/assets/6820342/10043081/6eefc5c0-61f0-11e5-90a4-8638d7e461e0.png">

a "zobrazit zoznam" vo footeri
<img width="320" alt="footer" src="https://cloud.githubusercontent.com/assets/6820342/10043085/7abfd5c0-61f0-11e5-932a-bec3a97f4062.png">

**Comment by j2ghz** [comment]
@lpk90901 takže registrovať necha v takych farbach ako je?

**Comment by j2ghz** [comment]
DUplicate #26

**Comment by lpk90901** [comment]
button "registracia" vyzera byt "left alined", mal by byt v ramci widgetu vycentrovany

<img width="420" alt="vycentrovat-button" src="https://cloud.githubusercontent.com/assets/6820342/10221743/7df9701e-6850-11e5-970b-e4319c2b46c5.png">
