### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by j2ghz** [j2ghz/ChcemVediet-Style-Guide#14]
* [ ] „Zapamataj si ma“ nie je nastylovane podla stylesheetu (vyplneny stav vid obrazok) – hlavne na mobile to vyzera divne.
* [x] Tiez vseobecny „input box“ [email, heslo] pouziva v hornej casti drop shadow – toto mozeme odstranit.

![image](https://cloud.githubusercontent.com/assets/1708197/9941792/dbe4f70e-5d77-11e5-96d9-81b8a03d669a.png)

**Comment by lpk90901** [comment]
"Prihlasit sa" button bude druha extra class-a, ktora bude pouzita len v tomto widgete.

**Comment by j2ghz** [comment]
@lpk90901 bolo by mozne urobit 4 SVGcka tych checkboxov (kombinacie zatrhnutia a hoveru)?

**Comment by j2ghz** [comment]
Duplicate #26

**Comment by lpk90901** [comment]
Pouzime teraz nastaveia browsera.
