### ISSUE TITLE
Fakty

### ISSUE THREAD

**Issue by j2ghz** [j2ghz/ChcemVediet-Style-Guide#15]
FAKTY – ikonky su ine ako v dizajne
Text „Portál chcemvediet.sk funguje v testovacej prevádzke“ je prilis blizko pri „BETA“ [tiez odtien sedej je iny?]

![image](https://cloud.githubusercontent.com/assets/1708197/9941797/e55f2728-5d77-11e5-97e3-3c2d996f8c6a.png)

**Comment by j2ghz** [comment]
@lpk90901 budu to obrazky alebo sa to mam pokusit vytvorit pomocou gulateho divu?

**Comment by martinmacko47** [comment]
nejde na to pouzit pramo badges? http://getbootstrap.com/components/#badges
