### ISSUE TITLE
"Vedeli ste?" carousel

### ISSUE THREAD

**Issue by j2ghz** [j2ghz/ChcemVediet-Style-Guide#17]
Pri widgete „Vedeli ste?“ = malo by stacit pouzit bezny
bootstrap carousel. Takze netreba nic nove programovat. Treba ho vsak
nastylovat samozrejme.

![image](https://cloud.githubusercontent.com/assets/1708197/9941819/0821885a-5d78-11e5-889d-cc2f9a485358.png)

**Comment by j2ghz** [comment]
@lpk90901 nedari sa mi vymysliet, ako urobit tu sipku (trojuholnik) ktora ma ukazovat na aktivny kruh

**Comment by martinmacko47** [comment]
priklad ako na trojuholnik pod divom: http://jsfiddle.net/9AbYc/1/

**Comment by martinmacko47** [comment]
Alebo ak to spravis takto: http://jsfiddle.net/9AbYc/
tak pomocou zmeny "margin-left: -50px;" vies tu sipku posuvat do strany aby bola nad gulickou

**Comment by j2ghz** [comment]
zle som to napisal, ako spravit trojuholnik viem, ide skor o to ako dat tie indikatory aby boli pod carouselom. Nakoniec sa mi podarilo ich posunut, ale tie sipky su fixne, a na presny pocet (2) stranok

**Comment by j2ghz** [comment]
tie sipky sedia len pri jednom konkretnom rozliseni, inak sa to rozhadze

**Comment by lpk90901** [comment]
Vyzera to teraz lepsie - pozerali sme to dnes s Martinom, spomenul ze by bolo dobre dat tomu elementu biely margin, aby neboli pri pohybe bubliny na seba "natlacene". Viem ze na tom este robis, cize to mozno mas v plane, len pisem o com sme sa dnes bavili..

Mozem taketo veci vysvetlit osobne na Skype..

**Comment by j2ghz** [comment]
prepisane do #32
