### ISSUE TITLE
Darcovia

### ISSUE THREAD

**Issue by j2ghz** [j2ghz/ChcemVediet-Style-Guide#19]
Vo footeri pod „Individuálny darcovia“ su znova rozdiely v stylovani buttonov:

![image](https://cloud.githubusercontent.com/assets/1708197/9941847/313b5270-5d78-11e5-997f-7446f33d6367.png)

**Comment by j2ghz** [comment]
#11

**Comment by lpk90901** [comment]
"zobrazit zoznam" by mala byt extra classa, ktora bude pouzita len tu a zatial nikde inde.

**Comment by lpk90901** [comment]
Zmenme hover na buttone "zobrazit zoznam":
modre pozadie je OK
text by mal byt biely

<img width="368" alt="hover-biely-text" src="https://cloud.githubusercontent.com/assets/6820342/10221369/46249422-684e-11e5-866b-697dd163a4c7.png">
