### ISSUE TITLE
Langauge

### ISSUE THREAD

**Issue by j2ghz** [j2ghz/ChcemVediet-Style-Guide#21]
„English“ nemá byt dropdown = ma sa po kliknuti zmenit na „Slovenčina“

![image](https://cloud.githubusercontent.com/assets/1708197/9941884/6a6cb250-5d78-11e5-83bd-aa94ef49852c.png)

**Comment by j2ghz** [comment]
@martinmacko47 akym zposobom sa budu prepinat jazyky? jeden html template pre kazdy jazyk?

**Comment by martinmacko47** [comment]
staticke html sprav, ako bude vyzerat pre slovencinu, anglicka verzia sa vygeneruje analogicky
