### ISSUE TITLE
Backgrounds

### ISSUE THREAD

**Issue by j2ghz** [j2ghz/ChcemVediet-Style-Guide#22]
Vsetky pozadia (tmavomodra v navigacii/hlavne vyhladavacie pole, sede pozadie – fakty/footer..) by mali byt full width – momentalne je vsetko spravene na 1190 px. Treba spravit spravnu sirku (responsive) uz teraz.

![image](https://cloud.githubusercontent.com/assets/1708197/9941897/81420aa2-5d78-11e5-8386-6e9e8a396f5b.png)

**Comment by j2ghz** [comment]
@mmmaly takze az ku kraji ma ist iba pozadie (nie uplne jednoduche), alebo aj content (velmi jednoduche)?

**Comment by mmmaly** [comment]
content
