### ISSUE TITLE
Mobilna verzia

### ISSUE THREAD

**Issue by j2ghz** [j2ghz/ChcemVediet-Style-Guide#24]
@mmmaly @martinmacko47 Ako to bude s mobilnou verziou? Zatial pracujem s verziou ze bude jedna stranka responsive, nechal som defaultne sirky z bootstrapu
`Extra small devices Phones (<768px)`
`Small devices Tablets (≥768px)`
`Medium devices Desktops (≥992px)`
`Large devices Desktops (≥1200px)`
Graficky navrh som dostal pre mobil a pre desktop. Mam to rozdelit tak ze <768px bude mobilna verzia a ≥768px bude desktopova? Alebo az 992px? Pripadne neni problem ich upravit globalne

**Comment by martinmacko47** [comment]
Preposlal som to Misi

**Comment by lpk90901** [comment]
Ahoj,

prosim daj tieto buttony ako primary:
<img width="926" alt="primary-button" src="https://cloud.githubusercontent.com/assets/6820342/10042796/1dba74fe-61ee-11e5-881d-50573e9ca202.png">

a vytvor dalsie dve klasy pre 2 druhy buttonov na homepage [ktore su ine z vizualnych dovodov len pre homepage]
- prihlasovanie na HP
- darcovia vo footeri [v podstate len ten "zobrazit zoznam" je iny, chcem prispiet je jeden z tych primary]

<img width="274" alt="homepage login" src="https://cloud.githubusercontent.com/assets/6820342/10042807/3bdd6f72-61ee-11e5-8545-291a56ebfee1.png">
<img width="320" alt="footer" src="https://cloud.githubusercontent.com/assets/6820342/10042810/3e6ae2a6-61ee-11e5-9767-7c2a1002f273.png">

Moze byt?

**Comment by lpk90901** [comment]
Ahojte,

podla mna mozeme dat <768px 1 stlpec a ≥768px responzivna desktopova

Michala
