### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by j2ghz** [j2ghz/ChcemVediet-Style-Guide#25]
Napadlo ma ze by mozno bolo lepsie ukladat vektorove obrazky ako SVG namiesto PNG, cim by sa zlepsila ich kvalita na stranke, nezavisle od velkosti obrazovky.

**Comment by lpk90901** [comment]
Ahoj Jozef, myslim ze chapem kde je problem.

Prebrali sme to s chalanmi.

Toto by mali byt 3 zakladne "primary" buttony:
<img width="926" alt="primary-button" src="https://cloud.githubusercontent.com/assets/6820342/10042675/0596a088-61ed-11e5-9846-9f917471de24.png">

Jedine buttony, ktore budu ine, su tieto 2 [z vizualnych dovodov]: 
- Login na homepage
- Darcovia vo footeri

<img width="274" alt="homepage login" src="https://cloud.githubusercontent.com/assets/6820342/10042696/3cc61142-61ed-11e5-8778-7ed3d7cd1243.png">
<img width="320" alt="footer" src="https://cloud.githubusercontent.com/assets/6820342/10042697/3f4e2dd2-61ed-11e5-84bb-8a0d09684125.png">

Pre tieto dva by si mohol vytvorit extra classy. Moze byt?

**Comment by lpk90901** [comment]
Ahoj, uploadla som to tu:
https://www.dropbox.com/s/2q43nkwqo0xp9j4/ChV_SVG.zip?dl=0

Da sa to pouzit?

**Comment by lpk90901** [comment]
Zda sa mi, ze uz si to cez SVG spravil?

**Comment by j2ghz** [comment]
Ja som si vyexportoval jeden z toho .ai aby som to otestoval.

**Comment by lpk90901** [comment]
daj vediet ak by to potreboval inak nez to je tu
https://www.dropbox.com/s/2q43nkwqo0xp9j4/ChV_SVG.zip?dl=0
