### ISSUE TITLE
Stanovit fixnu sirku stranky na desktope

### ISSUE THREAD

**Issue by lpk90901** [j2ghz/ChcemVediet-Style-Guide#31]
@j2ghz ako si mozes vsimnut na http://www.chcemvediet.sk/ - aj nova homepage by mala mat stanovenu maximalnu sirku na desktopovej verzii - momentalne sa stranka "roztahuje" nekonecne s oknom browsera [full width]

Vsetky nahlady boli urobene na maximalnu sirku 1190 - viem ze som v inom todo hovorila o "nekonecnom pozadi" - toto sa vsak ma tykat len pozadia, nie vsetkeho contentu - tri stlpce by nikdy nemali presiahnut sirku 1190 px

**Comment by j2ghz** [comment]
@lpk90901 v #22 som sa pytal a bolo povedane content, opravim

defaultne v bootstrape (http://getbootstrap.com/css/#grid-options) je to tak, ze  pre monitory >1200px je stranka 1170px, pre >992px je 970px atd.

mam teda pouzit obmedzenie sirky, ci racej `container` z bootstrapu?

k pozadiu: zmena na pozadie az do kraja ale content nie nieje uplne jednoducha, takze chcem byt presvedceny, ze myslime to same:
![capture](https://cloud.githubusercontent.com/assets/1708197/10245693/494dc3d2-690a-11e5-9b9d-a09880cd3c22.PNG)
(mspaint)

**Comment by j2ghz** [comment]
@lpk90901 http://j2ghz.github.io/ChcemVediet-Style-Guide/homepage.html momentalne je to vyriesene cez bootstrapovy `container`

**Comment by j2ghz** [comment]
prepisane do #32

**Comment by lpk90901** [comment]
Ahoj,
myslim ze uz to bude super, jedine uplne najspodnejsia cast footeru (tmavoseda), nie je full width

<img width="248" alt="screen shot 2015-10-23 at 15 48 17" src="https://cloud.githubusercontent.com/assets/6820342/10694280/8e1c04f8-799d-11e5-99f1-a6d03a0e4f69.png">
