### ISSUE TITLE
Mobile width bug

### ISSUE THREAD

**Issue by j2ghz** [j2ghz/ChcemVediet-Style-Guide#33]
Ked otvorim stranku v chrome, zapnem developer tools, zobrazenie pre mobily a znova nacitam stranku (F5), zobrazi sa takto:
![image](https://cloud.githubusercontent.com/assets/1708197/10265016/5bac812e-6a1f-11e5-90e5-b72a08fae6de.png)
Ked potom kliknem na zmenit orientaciu na sirku a zase spat, zobrazi sa spravne:
![image](https://cloud.githubusercontent.com/assets/1708197/10265018/863a1596-6a1f-11e5-81ed-a96d5d4c1dec.png)

**Comment by lpk90901** [comment]
S Martinom sme sa dohodli, ze to nechame teraz tak, a na mobile to pravdepodobne vynechame, kedze je to problematicky element.
