### ISSUE TITLE
Images for stats

### ISSUE THREAD

**Issue by j2ghz** [j2ghz/ChcemVediet-Style-Guide#56]
![image](https://cloud.githubusercontent.com/assets/1708197/10524120/2ff76cc0-737e-11e5-8a0e-af608504ec26.png)
tazko sa to robilo, nevyzera to moc dobre a pri urcitych sirkach to vyzera takto
som za nahradu za svg
(tej ikony v kolecku)

**Comment by martinmacko47** [comment]
Neviem ako Miska presne myslela, ako to ma vyzerat pri roznych rozliseniach, zle ocakaval by som, ze pri uzsom rozliseni bude bud a) mensi font, alebo b) menej textu, alebo c) jednotlive stlpce budu pod sebou. Elementu, v ktorom je ikonka staci nastavit rovnaku explicitnu sirku a vysku a bude to kruh. Na toto pouzivat svg je zbytocna komplikacia.

**Comment by martinmacko47** [comment]
Navyse neviem nakolko sa na svg mozeme spolahnut, lebo co viem, tak IE ma s tym nejake issues a nevie ho spravne skalovat.

**Comment by mmmaly** [comment]
ok, urobme to jednoducho, nastav proste sirku div-u
