### ISSUE TITLE
Font sizes

### ISSUE THREAD

**Issue by j2ghz** [j2ghz/ChcemVediet-Style-Guide#9]
* [x] *vsade* su nastavene nespravne velkosti fontu (vacsinou vacsi font, nez v nahladoch) -- priklad nadpis Co chces vediet, ktory sa rozbije do 2 riadkov kvoli tomu. To treba fixnut globalne.

![image](https://cloud.githubusercontent.com/assets/1708197/9941648/130b78da-5d77-11e5-9f53-aeb705c51a1d.png)

* [x] +navrhy neobsahovali ako sa ma zmenit input field po zadani textu, tu je nahlad:
innner shadow # 05256d [opacity 25%]

![image](https://cloud.githubusercontent.com/assets/1708197/9941653/1a7ebc8a-5d77-11e5-9f9f-fa424ae84777.png)

**Comment by j2ghz** [comment]
Ako velke maju fonty byť? Napisane som to v nahladoch nevidel a na mojej obrazovke vyzeraju dost podobne
![capture](https://cloud.githubusercontent.com/assets/1708197/9977809/61d35aac-5f14-11e5-95b4-5c3b5db07615.PNG)

**Comment by lpk90901** [comment]
Ahoj, co sa tyka textu/nadpisu "Co chces vediet" - to je OK, netreba to riesit.

Co je vacsi problem:
Da za variovat text v input fielde - "Hladaj v infoziadostiach" [na mobile to nedava zmysel].

**Comment by lpk90901** [comment]
Ahoj,

* pouzime vo vyhladavacom okne text "Hladaj v infoziadostiach"
* ked uzivatel klikne do policka "Hladaj v infoziadostiach", text by mal zmiznut [momentalne tam zostava a zmizne az ked zacnem pisat]

**Comment by martinmacko47** [comment]
imho spravit, aby text zmizol po kliknuti je zbytocne komplikovane... je to vec browsru ako zobrazuje placeholder... nechajme to tak, ze placeholder zmizne az ked zacne pisat

**Comment by martinmacko47** [comment]
Tak predsa, je to matuce, ked tam svieti placeholver, ked na to kliknem. Dajme ho prec, ked je field aktivny. Malo by sa to dat tak, ze pre :active field nastavime aby placeholder mal rovnaku farbu ako pozadie, alebo tak nejak...

**Comment by j2ghz** [comment]
nakoniec to chcelo :focus, :active bol aktivny len kym som drzal mys.

**Comment by j2ghz** [comment]
@lpk90901 len ten jeden input ci vsetky mam tak upravit?

**Comment by lpk90901** [comment]
Vsetky by sa mali chovat rovnako. Cize @j2ghz  - ano! Vdaka!
